version: "3.9"
services:
  prisma-db:
    container_name: prisma-db
    image: postgres:13
    ports:
      - "5432:5432"
    volumes:
      - prisma-store:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: root
      POSTGRES_PASSWORD: prisma2020
      POSTGRES_DB: prisma
      POSTGRES_INITDB_ARGS: "--encoding=UTF-8"
      TZ: "Asia/Tokyo"

volumes:
  prisma-store:
    driver: local
