name: Run linter
on: pull_request
jobs:
  Run-ESlint-Job:
    timeout-minutes: 10
    runs-on: ubuntu-latest
    steps:
      # Nodeを準備
      - name: Setup Node.js
        uses: actions/setup-node@v2
        with:
          node-version: "16"
      # ブランチ移動
      - name: Checkout current branch
        uses: actions/checkout@v2
        with:
          ref: ${{ github.event.pull_request.head.sha }}
      # yarn install
      - name: Install dependencies
        run: yarn
      # run ESLint
      - name: Run ESLint
        run: yarn lint
